# Generated from ghostty/.config/ghostty/config -- do not hand-edit.
# Regenerate with the awk command in the migration plan, Task 6.
[
  "SauceCodePro Nerd Font"
  "Noto Sans Mono"
  "Noto Sans Mono CJK SC"
  "Noto Sans"
  "Noto Sans CJK SC"
  "Noto Sans Symbols"
  "Noto Sans Symbols 2"
  "Noto Sans Runic"
  "Noto Sans Math"
  "Noto Sans Adlam"
  "Noto Sans Anatolian Hieroglyphs"
  "Noto Sans Arabic"
  "Noto Sans Armenian"
  "Noto Sans Avestan"
  "Noto Sans Balinese"
  "Noto Sans Bamum"
  "Noto Sans Bassa Vah"
  "Noto Sans Batak"
  "Noto Sans Bengali"
  "Noto Sans Bhaiksuki"
  "Noto Sans Brahmi"
  "Noto Sans Buginese"
  "Noto Sans Buhid"
  "Noto Sans Canadian Aboriginal"
  "Noto Sans Carian"
  "Noto Sans Caucasian Albanian"
  "Noto Sans Chakma"
  "Noto Sans Cham"
  "Noto Sans Cherokee"
  "Noto Sans Chorasmian"
  "Noto Sans Coptic"
  "Noto Sans Cuneiform"
  "Noto Sans Cypriot"
  "Noto Sans Cypro Minoan"
  "Noto Sans Deseret"
  "Noto Sans Devanagari"
  "Noto Sans Duployan"
  "Noto Sans Egyptian Hieroglyphs"
  "Noto Sans Elbasan"
  "Noto Sans Elymaic"
  "Noto Sans Ethiopic"
  "Noto Sans Georgian"
  "Noto Sans Glagolitic"
  "Noto Sans Gothic"
  "Noto Sans Grantha"
  "Noto Sans Gujarati"
  "Noto Sans Gunjala Gondi"
  "Noto Sans Gurmukhi"
  "Noto Sans Hanifi Rohingya"
  "Noto Sans Hanunoo"
  "Noto Sans Hatran"
  "Noto Sans Hebrew"
  "Noto Sans Imperial Aramaic"
  "Noto Sans Indic Siyaq Numbers"
  "Noto Sans Inscriptional Pahlavi"
  "Noto Sans Inscriptional Parthian"
  "Noto Sans Javanese"
  "Noto Sans Kaithi"
  "Noto Sans Kannada"
  "Noto Sans Kawi"
  "Noto Sans Kayah Li"
  "Noto Sans Kharoshthi"
  "Noto Sans Khmer"
  "Noto Sans Khojki"
  "Noto Sans Khudawadi"
  "Noto Sans Lao"
  "Noto Sans Lepcha"
  "Noto Sans Limbu"
  "Noto Sans Linear A"
  "Noto Sans Linear B"
  "Noto Sans Lisu"
  "Noto Sans Lycian"
  "Noto Sans Lydian"
  "Noto Sans Mahajani"
  "Noto Sans Malayalam"
  "Noto Sans Mandaic"
  "Noto Sans Manichaean"
  "Noto Sans Marchen"
  "Noto Sans Masaram Gondi"
  "Noto Sans Mayan Numerals"
  "Noto Sans Medefaidrin"
  "Noto Sans Meetei Mayek"
  "Noto Sans Mende Kikakui"
  "Noto Sans Meroitic"
  "Noto Sans Miao"
  "Noto Sans Modi"
  "Noto Sans Mongolian"
  "Noto Sans Mro"
  "Noto Sans Multani"
  "Noto Sans Myanmar"
  "Noto Sans Nabataean"
  "Noto Sans Nag Mundari"
  "Noto Sans Nandinagari"
  "Noto Sans New Tai Lue"
  "Noto Sans Newa"
  "Noto Sans NKo"
  "Noto Sans Nushu"
  "Noto Sans Ogham"
  "Noto Sans Ol Chiki"
  "Noto Sans Old Hungarian"
  "Noto Sans Old Italic"
  "Noto Sans Old North Arabian"
  "Noto Sans Old Permic"
  "Noto Sans Old Persian"
  "Noto Sans Old Sogdian"
  "Noto Sans Old South Arabian"
  "Noto Sans Old Turkic"
  "Noto Sans Oriya"
  "Noto Sans Osage"
  "Noto Sans Osmanya"
  "Noto Sans Pahawh Hmong"
  "Noto Sans Palmyrene"
  "Noto Sans Pau Cin Hau"
  "Noto Sans PhagsPa"
  "Noto Sans Phoenician"
  "Noto Sans Psalter Pahlavi"
  "Noto Sans Rejang"
  "Noto Sans Samaritan"
  "Noto Sans Saurashtra"
  "Noto Sans Sharada"
  "Noto Sans Shavian"
  "Noto Sans Siddham"
  "Noto Sans SignWriting"
  "Noto Sans Sinhala"
  "Noto Sans Sogdian"
  "Noto Sans Sora Sompeng"
  "Noto Sans Soyombo"
  "Noto Sans Sundanese"
  "Noto Sans Sunuwar"
  "Noto Sans Syloti Nagri"
  "Noto Sans Syriac"
  "Noto Sans Tagalog"
  "Noto Sans Tagbanwa"
  "Noto Sans Tai Le"
  "Noto Sans Tai Tham"
  "Noto Sans Tai Viet"
  "Noto Sans Takri"
  "Noto Sans Tamil"
  "Noto Sans Tamil Supplement"
  "Noto Sans Tangsa"
  "Noto Sans Telugu"
  "Noto Sans Thaana"
  "Noto Sans Thai"
  "Noto Sans Tifinagh"
  "Noto Sans Tirhuta"
  "Noto Sans Ugaritic"
  "Noto Sans Vai"
  "Noto Sans Vithkuqi"
  "Noto Sans Wancho"
  "Noto Sans Warang Citi"
  "Noto Sans Yi"
  "Noto Sans Zanabazar Square"
  "Noto Serif"
  "Noto Serif CJK SC"
  "Noto Color Emoji"
]
