{ pkgs, ... }:
{
  environment.systemPackages = [
    pkgs.age
    pkgs.bat
    pkgs.cargo
    pkgs.clang-tools
    pkgs.clippy
    pkgs.cmake
    pkgs.cmatrix
    pkgs.codespell
    pkgs.coreutils
    pkgs.cowsay
    pkgs.csvkit
    pkgs.fastfetch
    pkgs.fd
    pkgs.fx
    pkgs.fzf
    pkgs.gawk
    pkgs.getopt
    pkgs.gh
    pkgs.git-quick-stats
    pkgs.glab
    pkgs.gnused
    pkgs.go
    pkgs.go-task
    pkgs.gradle
    pkgs.htop
    pkgs.imagemagick
    pkgs.jdk21
    pkgs.jira-cli-go
    pkgs.jq
    pkgs.k9s
    pkgs.lcov
    pkgs.lefthook
    pkgs.lftp
    pkgs.markdownlint-cli2
    pkgs.most
    pkgs.mpv
    pkgs.ncdu
    pkgs.neo
    pkgs.neovim
    pkgs.newsboat
    pkgs.ninja
    pkgs.opencode
    pkgs.postgresql_17
    pkgs.prettier
    pkgs.pv
    pkgs.python3Packages.fonttools
    pkgs.ripgrep
    pkgs.ruff
    pkgs.rust-analyzer
    pkgs.rustc
    pkgs.rustfmt
    pkgs.shellcheck
    pkgs.shfmt
    pkgs.stow
    pkgs.taplo
    pkgs.tmux
    pkgs.tree
    pkgs.tree-sitter
    pkgs.uv
    pkgs.vim
    pkgs.whisper-cpp
    pkgs.yq-go
    pkgs.zoxide
    pkgs.zunit
  ];
}
